version: '3.1'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
      - "8043:8043"
#    stop_grace_period: 30s
    secrets:
      - gateway-password
    #volumes:
      #- /home/welljona/SmartTouchDocker/modules:/modules
      #- /home/welljona/SmartTouchDocker/Dev_V0_Ignition-backup-20230505-1118.gwbk:/restore.gwbk
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_RESTORE_DISABLED=true
      - GATEWAY_ADMIN_USERNAME=admin
      - GATEWAY_ADMIN_PASSWORD=password
      - IGNITION_EDITION=edge
      - TZ=America/Chicago
      - DISABLE_QUICKSTART=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      -p 8088:8088


secrets:
  gateway-password:
    file: secrets/gateway-password

